# Generated by Django 3.1.5 on 2021-07-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
